keycloak:
  auth-server-url: 'http://85.204.43.222:4200/auth'
  credentials:
    secret: ec86d65e-bdf7-41c9-8908-8cf863f9913e
  realm: test
  resource: maxcup
  ssl-required: none
  bearer-only: true
  use-resource-role-mappings: true
  cors: true
#  redirect-uris:
#    - 'http://localhost:8080/*'
server:
  #  servlet:
  #    context-path: /maxcup
  port: '8092'
  address: '0.0.0.0'
spring:
  kafka:
    producer:
      bootstrap-servers: "85.204.43.222:9092"
      topic: "alert-topic"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer "
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer "
connector:
  resource: 'admin-cli'
  credentials:
    secret: '71cb4b28-b6b7-44b7-b36e-3cf394f15042'

